length_in_x: 2
length_in_y: 2
position_x: 0.0
position_y: 0.0
resolution: 0.05
min_variance: 0.000009
max_variance: 0.01
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.0000009
enable_visibility_cleanup: false
min_update_rate: 20
fused_map_publishing_rate: 20
relocate_rate: 20
initialize_elevation_map: true
init_submap_height_offset: 0.0001
target_frame_init_submap: "/a1_world"
